### ISSUE TITLE
 java.lang.RuntimeException: Could not invoke RNAudioRecorderPlayer.pauseRecorder

### ISSUE THREAD

**Issue by RahulKatkade** [hyochan/react-native-nitro-sound#383]
App crash on click pause button in Android 6 

### Version of react-native-audio-recorder-player
3.1.1

### Version of React Native
0.64.1
### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
pause the recording. 

### Actual behavior
application crash click on pause button.

### Steps to reproduce the behavior
1. start Recording 
2. click on pause button 

Exception in native call
    java.lang.RuntimeException: Could not invoke RNAudioRecorderPlayer.pauseRecorder
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:148) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.NoSuchMethodError: No virtual method pause()V in class Landroid/media/MediaRecorder; or its super classes (declaration of 'android.media.MediaRecorder' appears in /system/framework/framework.jar)

**Comment by hyochan** [comment]
This issue was filed against the pre-Nitro `react-native-audio-recorder-player` API. This repo has since been completely rewritten on top of [react-native-nitro-modules](https://github.com/mrousavy/nitro) as **react-native-nitro-sound**.

If this still reproduces on the latest `react-native-nitro-sound`, please open a fresh issue with:
- Library version (`react-native-nitro-sound`)
- React Native version
- Platform (iOS / Android)
- Minimal repro steps and logs

Closing as `stale-legacy` for now.

> 🤖 AI-native maintenance. See #787 for context.

**Comment by hyochan** [comment]
Closing as part of a stale-legacy sweep.

This issue was filed against the pre-Nitro `react-native-audio-recorder-player` codebase, hasn't seen activity in a long time, and the underlying API has since been rewritten on top of [Nitro Modules](https://github.com/mrousavy/nitro). Most legacy code paths referenced here no longer exist.

If this still affects you on **`react-native-nitro-sound` v3+**, please:
1. Open a fresh issue with a minimal repro on the current version, and
2. Include your iOS/Android version, RN version, and `nitro-modules` version.

Thanks for the original report — closing to keep the queue focused on actionable, current-version reports. 🙏

> 🤖 Auto-closed by daily triage.
